// config.js
window.BioConfig = {
  modelRegistry: {
    birdnet: {
      name: "BirdNET",
      version: 2.4,
      about: "https://birdnet.cornell.edu/",
      modelUrl: "https://huggingface.co/justinchuby/BirdNET-onnx/resolve/main/model.onnx",
      labelsUrl: "https://huggingface.co/justinchuby/BirdNET-onnx/resolve/main/BirdNET_GLOBAL_6K_V2.4_Labels.txt",
      sampleRate: 48000,
      windowSize: 3,
      softmax: false,
      inputIndex: 0,
      outputIndex: 0,
      skipLabelsHeader: 0
    },
    perch: {
      name: "Perch",
      version: 2.0,
      about: "https://www.kaggle.com/models/google/bird-vocalization-classifier",
      modelUrl: "https://huggingface.co/justinchuby/Perch-onnx/resolve/main/perch_v2.onnx",
      labelsUrl: "https://huggingface.co/cgeorgiaw/Perch/resolve/main/assets/labels.csv",
      sampleRate: 32000,
      windowSize: 5,
      softmax: true,
      inputIndex: 0,
      outputIndex: 3,
      skipLabelsHeader: 1
    }
  },
  uiText: {
    en:{
      language: "English",
      extensionName: "iNaturalist Sound Classifier",
      bioacousticModel: "Bioacoustic Model:",
      bioacousticModelHelp: "Bioacoustic models are selected based on the taxa they are able to classify. Some models are available in the registry and the user can also add custom models in the advanced settings section below.",
      analysisButton: "Run Analysis",
      advancedSettings: "+ Advanced settings",
      confidence: "Confidence Threshold: ",
      confidenceHelp : "This parameter relates to the output score of the model which ranges between 0 and 1. Any detection with score below this threshold is ignored.",
      overlap: "Overlap: ",
      overlapHelp: "This parameter corresponds to the percentage of overlap between analysis windows within the observation sound. Each model has its own specific analysis window duration.",
      customModel: "Add custom model (JSON):",
      customModelHelp: "The user is able to add a custom model by providing all model properties following the JSON format below.",
      addCustomButton: "Add to List",
      clearLogsButton: "Clear Logs",
      setLanguage: "Language:",
      setLanguageHelp: "Select a language for the extension. This configuration will be saved in cache",
      initLog: "Select a model and press",
      tmpRunButton: "Analyzing...",
      analyzingSound: "Analyzing sound",
      timeCell: "Time Window",
      speciesCell: "Species",
      confidenceCell: "Confidence",
      topDetection: "Top detection",
      validatingDetection: "Validating top detection species location",
      checkingGBIF: "Checking GBIF coordinate range for",
      coordNotFound: "Could not find coordinates for this observation.",
      fetchGBIFError: "Could not fetch GBIF range for",
      withinGBIF: "✓ Within GBIF bounding box for this species",
      outsideGBIF: "⚠ Outside GBIF bounding box for this species",
      noDetection: "No species detected above threshold.",
      endOfAnalysis: "End of Analysis for this sound.",
      selectedModel: "Selected model",
      windowDuration: "Duration of analysis window",
      sampleRate: "Sample rate",
      inputIndex: "Input index",
      outputIndex: "Output index",
      usingSoftmax: "Using softmax",
      sources: "Sources",
      preparingModel: "Preparing model session",
      loadingSuccess: "Model successfully loaded to memory",
      modelNotFound: "Not found in cache",
      downloadingModel: "Downloading",
      savedModel: "Saved to cache",
      loadedModel: "Loaded from cache"
    },
    pt_br: {
      language: "Português (BR)",
      extensionName: "iNaturalist Sound Classifier",
      bioacousticModel: "Modelo Bioacústico:",
      bioacousticModelHelp: "Os modelos bioacústicos são selecionados com base nos táxons que conseguem classificar. Alguns modelos estão disponíveis no registro e o usuário também pode adicionar modelos personalizados na seção de configurações avançadas abaixo.",
      analysisButton: "Iniciar Análise",
      advancedSettings: "+ Configurações Avançadas",
      confidence: "Mínimo Nível de Confiança: ",
      confidenceHelp : "Este parâmetro relaciona-se com a pontuação de saída do modelo, que varia entre 0 e 1. Qualquer detecção com pontuação abaixo desse limite é ignorada.",
      overlap: "Overlap: ",
      overlapHelp: "Este parâmetro corresponde à porcentagem de sobreposição entre as janelas temporais de análise dentro da observação sonora.",
      customModel: "Adicione um modelo customizado (JSON):",
      customModelHelp: "O usuário pode adicionar um modelo personalizado fornecendo todas as propriedades do modelo seguindo o formato JSON abaixo.",
      addCustomButton: "Adicionar à Lista",
      clearLogsButton: "Limpar Console",
      setLanguage: "Idioma:",
      setLanguageHelp: "Selecione um idioma para a extensão. Essa configuração será salva no cache do navegador.",
      initLog: "Selecione um modelo e clique em",
      tmpRunButton: "Analisando...",
      analyzingSound: "Analisando som",
      timeCell: "Intervalo",
      speciesCell: "Espécie",
      confidenceCell: "Confiança",
      topDetection: "Melhor detecção",
      validatingDetection: "Validação da localização da espécie com melhor detecção",
      checkingGBIF: "Verificando as coordenadas no GBIF para",
      coordNotFound: "Não foi possível encontrar as coordenadas para esta observação.",
      fetchGBIFError: "Não foi possível obter informações no GBIF para",
      withinGBIF: "✓ Dentro da área delimitada pelo GBIF para esta espécie",
      outsideGBIF: "⚠ Fora da área delimitadora do GBIF para esta espécie",
      noDetection: "Nenhuma espécie detectada acima do valor mínimo de confiança.",
      endOfAnalysis: "Fim da Análise para este som.",
      selectedModel: "Modelo selecionado",
      windowDuration: "Duração da janela de análise",
      sampleRate: "Frequência de amostragem",
      inputIndex: "Índice de entrada",
      outputIndex: "Índice de saída",
      usingSoftmax: "Usando softmax",
      sources: "Fontes",
      preparingModel: "Preparando modelo para análise",
      loadingSuccess: "Modelo carregado com sucesso na memória.",
      modelNotFound: "Arquivo não encontrado na cache",
      downloadingModel: "Baixando",
      savedModel: "Salvo na cache",
      loadedModel: "Arquivo encontrado na cache"
    }
  },
  overlapPercentage: 0,
  confidenceThreshold: 0.5,
  timeCellWidth: 15,
  speciesCellWidth: 32,
  confidenceCellWidth: 12
};

// Point ORT to WASM folder
ort.env.wasm.wasmPaths = chrome.runtime.getURL("onnx/");